#################################################################
#  Parameters - SA-SFT
#################################################################

tokenizer_path: "model/qwen3-0.6b-base"
model_name_or_path:  "model/qwen3-0.6b-base"
comp_id: "answer"
instruction: >
  You are given a question and references which may or may not help answer the question.
  Please answer the question in as few words as possible by using the information provided in the references that is relevant in answering the question.

chat_prompt_template: >
  question: {question}\n
  context: {context}\n

model_save_path: "models/SA/SA_sft"
log_path: "logs/SA/SA_sft.log"
model_warmup_ratio: 0.01
model_max_length: 512
model_max_target_length: 75
model_num_epochs: 1
model_batch_size: 1
model_eval_batch_size: 1
model_learningrate: 0.000001
top_k: 50
train: "train"
train_type: SFT
peft: True
pad: True

sample_size: 5

input_ag_train_path: "data/train/QU_praise/sampling/QU_init/ERF_init/erf_train_.jsonl"
sft_data_path: "data/train/AG_praise/ag_sft_data.json"

input_ag_inference_path: "data/eval/QU_praise/ERF_praise/erf_dev.jsonl"
output_ag_inference_path: "data/eval/QU_praise/ERF_praise/AG_praise/ag_dev.json"



